name: currency_dart
description: "Flutter and Dart package to get All currencies and details"
version: 0.0.1
homepage: https://github.com/ali-you
repository: https://github.com/ali-you/info-json
documentation: https://github.com/ali-you/info-json
issue_tracker: https://github.com/ali-you/info-json/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
